In [1]:
import numpy as np
import random

In [2]:
nums = np.zeros((3,3), dtype = np.int8)

In [3]:
nums

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [4]:
nums[1,1] = 1

In [5]:
nums

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int8)

In [6]:
nums

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int8)

In [7]:
nums[1:2]

array([[0, 1, 0]], dtype=int8)

In [8]:
np.sum(nums[1:2])

1

In [9]:
np.sum(nums[:,1:2])

1

In [10]:
range(3)

range(0, 3)

In [11]:
def test_loop():
    for i in range(3):
        print(i)

In [12]:
test_loop()

0
1
2


In [13]:
sum(np.diagonal(nums))

1

In [14]:
sum(np.fliplr(nums).diagonal())

1

In [15]:
legal = []
for i in range(9):
    row = i // 3
    col = i % 3
    if nums[row, col] == 0:
        legal.append(i)

legal

[0, 1, 2, 3, 5, 6, 7, 8]

In [16]:
len(legal)

8

In [17]:
choice = [1,1]
nums[choice[0],choice[1]]

1

In [18]:
choice[1]

1

In [19]:
nums[1,1]

1

In [20]:
random.randint(1,3)

3

In [21]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
