In [2]:
import numpy as np

In [3]:
nums = np.zeros((3,3), dtype = np.int8)

In [4]:
nums

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [22]:
nums[1,1] = 1

In [23]:
nums

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 0]], dtype=int8)

In [27]:
nums

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 0]], dtype=int8)

In [8]:
nums[1:2]

array([[0, 0, 0]], dtype=int8)

In [9]:
np.sum(nums[1:2])

0

In [10]:
np.sum(nums[:,1:2])

0

In [11]:
range(3)

range(0, 3)

In [12]:
def test_loop():
    for i in range(3):
        print(i)

In [13]:
test_loop()

0
1
2


In [14]:
sum(np.diagonal(nums))

0

In [15]:
sum(np.fliplr(nums).diagonal())

1

In [26]:
legal = []
for i in range(9):
    row = i // 3
    col = i % 3
    if nums[row, col] == 0:
        legal.append(i)

legal

[0, 1, 3, 5, 6, 7, 8]

In [25]:
len(legal)

7

In [39]:
choice = [1,1]
nums[choice[0],choice[1]]

1

In [36]:
choice[1]

1

In [35]:
nums[1,1]

1