In [1]:
import numpy as np

In [5]:
nums = np.zeros((3,3), dtype = np.int8)

In [6]:
nums

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [46]:
nums[0,2] = 1

In [47]:
nums

array([[0, 0, 1],
       [0, 2, 2],
       [0, 0, 0]], dtype=int8)

In [16]:
nums

array([[0, 0, 0],
       [0, 2, 0],
       [0, 0, 0]], dtype=int8)

In [26]:
nums[1:2]

array([[0, 2, 2]], dtype=int8)

In [34]:
np.sum(nums[1:2])

4

In [33]:
np.sum(nums[:,1:2])

2

In [35]:
range(3)

range(0, 3)

In [41]:
def test_loop():
    for i in range(3):
        print(i)

In [42]:
test_loop()

0
1
2


In [53]:
sum(np.diagonal(nums))

2

In [54]:
sum(np.fliplr(nums).diagonal())

3